// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqcpNfuOLGLBR5abULGXgM2Y0cn0DgFL4',
    appId: '1:124240395013:web:5ba524c69f774a0f69156c',
    messagingSenderId: '124240395013',
    projectId: 'melhoresalunosnoite',
    authDomain: 'melhoresalunosnoite.firebaseapp.com',
    storageBucket: 'melhoresalunosnoite.appspot.com',
    measurementId: 'G-TP6LQ731XN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3yqMuo6y7czFoqnCTb0J34LdVxZiq5bc',
    appId: '1:124240395013:android:4e604c456aa3eb2269156c',
    messagingSenderId: '124240395013',
    projectId: 'melhoresalunosnoite',
    storageBucket: 'melhoresalunosnoite.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUlWl03u1GaGoE2rr3VUs7H_0RXNZE5zc',
    appId: '1:124240395013:ios:1e2a3bca65c1beb169156c',
    messagingSenderId: '124240395013',
    projectId: 'melhoresalunosnoite',
    storageBucket: 'melhoresalunosnoite.appspot.com',
    iosClientId: '124240395013-m2sbl5t2ll0h02c9ert2ub8np8i8d0tl.apps.googleusercontent.com',
    iosBundleId: 'br.com.paulofelix.flutterFirebaseTeste',
  );
}
